USE shopping_cart_localization;


INSERT INTO localization_strings (`key`, value, language) VALUES
                                                              ('app.title', 'Shopping Cart Application', 'en'),
                                                              ('label.language', 'Select Language', 'en'),
                                                              ('label.itemName', 'Item Name', 'en'),
                                                              ('label.price', 'Price', 'en'),
                                                              ('label.quantity', 'Quantity', 'en'),
                                                              ('label.overallTotal', 'Overall Total', 'en'),
                                                              ('prompt.itemName', 'Enter item name', 'en'),
                                                              ('prompt.price', 'Enter price', 'en'),
                                                              ('prompt.quantity', 'Enter quantity', 'en'),
                                                              ('button.addItem', 'Add Item', 'en'),
                                                              ('button.calculate', 'Calculate', 'en'),
                                                              ('button.clear', 'Clear', 'en'),
                                                              ('button.save', 'Save Cart', 'en'),
                                                              ('table.name', 'Name', 'en'),
                                                              ('table.price', 'Price', 'en'),
                                                              ('table.quantity', 'Quantity', 'en'),
                                                              ('table.total', 'Total', 'en'),
                                                              ('default.itemName', 'Item', 'en'),
                                                              ('alert.invalidTitle', 'Invalid input', 'en'),
                                                              ('alert.invalidNonNegative', 'Price and quantity must be non-negative.', 'en'),
                                                              ('alert.invalidNumber', 'Please enter a valid price and quantity.', 'en'),
                                                              ('alert.successTitle', 'Success', 'en'),
                                                              ('alert.errorTitle', 'Error', 'en'),
                                                              ('message.saved', 'Cart saved successfully!', 'en'),
                                                              ('message.error', 'Something went wrong.', 'en');


INSERT INTO localization_strings (`key`, value, language) VALUES
                                                              ('app.title', 'Ostoskori-sovellus', 'fi'),
                                                              ('label.language', 'Valitse kieli', 'fi'),
                                                              ('label.itemName', 'Tuotteen nimi', 'fi'),
                                                              ('label.price', 'Hinta', 'fi'),
                                                              ('label.quantity', 'Määrä', 'fi'),
                                                              ('label.overallTotal', 'Kokonaishinta', 'fi'),
                                                              ('prompt.itemName', 'Anna tuotteen nimi', 'fi'),
                                                              ('prompt.price', 'Anna hinta', 'fi'),
                                                              ('prompt.quantity', 'Anna määrä', 'fi'),
                                                              ('button.addItem', 'Lisää tuote', 'fi'),
                                                              ('button.calculate', 'Laske', 'fi'),
                                                              ('button.clear', 'Tyhjennä', 'fi'),
                                                              ('button.save', 'Tallenna kori', 'fi'),
                                                              ('table.name', 'Nimi', 'fi'),
                                                              ('table.price', 'Hinta', 'fi'),
                                                              ('table.quantity', 'Määrä', 'fi'),
                                                              ('table.total', 'Yhteensä', 'fi'),
                                                              ('default.itemName', 'Tuote', 'fi'),
                                                              ('alert.invalidTitle', 'Virheellinen syöte', 'fi'),
                                                              ('alert.invalidNonNegative', 'Hinnan ja määrän täytyy olla nolla tai enemmän.', 'fi'),
                                                              ('alert.invalidNumber', 'Anna kelvollinen hinta ja määrä.', 'fi'),
                                                              ('alert.successTitle', 'Onnistui', 'fi'),
                                                              ('alert.errorTitle', 'Virhe', 'fi'),
                                                              ('message.saved', 'Ostoskori tallennettiin onnistuneesti!', 'fi'),
                                                              ('message.error', 'Jokin meni pieleen.', 'fi');


INSERT INTO localization_strings (`key`, value, language) VALUES
                                                              ('app.title', 'Kundvagnsapplikation', 'sv'),
                                                              ('label.language', 'Välj språk', 'sv'),
                                                              ('label.itemName', 'Produktnamn', 'sv'),
                                                              ('label.price', 'Pris', 'sv'),
                                                              ('label.quantity', 'Antal', 'sv'),
                                                              ('label.overallTotal', 'Totalt pris', 'sv'),
                                                              ('prompt.itemName', 'Ange produktnamn', 'sv'),
                                                              ('prompt.price', 'Ange pris', 'sv'),
                                                              ('prompt.quantity', 'Ange antal', 'sv'),
                                                              ('button.addItem', 'Lägg till produkt', 'sv'),
                                                              ('button.calculate', 'Beräkna', 'sv'),
                                                              ('button.clear', 'Rensa', 'sv'),
                                                              ('button.save', 'Spara kundvagn', 'sv'),
                                                              ('table.name', 'Namn', 'sv'),
                                                              ('table.price', 'Pris', 'sv'),
                                                              ('table.quantity', 'Antal', 'sv'),
                                                              ('table.total', 'Totalt', 'sv'),
                                                              ('default.itemName', 'Produkt', 'sv'),
                                                              ('alert.invalidTitle', 'Ogiltig inmatning', 'sv'),
                                                              ('alert.invalidNonNegative', 'Pris och antal måste vara noll eller mer.', 'sv'),
                                                              ('alert.invalidNumber', 'Ange ett giltigt pris och antal.', 'sv'),
                                                              ('alert.successTitle', 'Lyckades', 'sv'),
                                                              ('alert.errorTitle', 'Fel', 'sv'),
                                                              ('message.saved', 'Kundvagnen sparades.', 'sv'),
                                                              ('message.error', 'Något gick fel.', 'sv');


INSERT INTO localization_strings (`key`, value, language) VALUES
                                                              ('app.title', 'ショッピングカートアプリ', 'ja'),
                                                              ('label.language', '言語を選択', 'ja'),
                                                              ('label.itemName', '商品名', 'ja'),
                                                              ('label.price', '価格', 'ja'),
                                                              ('label.quantity', '数量', 'ja'),
                                                              ('label.overallTotal', '合計金額', 'ja'),
                                                              ('prompt.itemName', '商品名を入力', 'ja'),
                                                              ('prompt.price', '価格を入力', 'ja'),
                                                              ('prompt.quantity', '数量を入力', 'ja'),
                                                              ('button.addItem', '商品を追加', 'ja'),
                                                              ('button.calculate', '計算', 'ja'),
                                                              ('button.clear', 'クリア', 'ja'),
                                                              ('button.save', 'カートを保存', 'ja'),
                                                              ('table.name', '名前', 'ja'),
                                                              ('table.price', '価格', 'ja'),
                                                              ('table.quantity', '数量', 'ja'),
                                                              ('table.total', '合計', 'ja'),
                                                              ('default.itemName', '商品', 'ja'),
                                                              ('alert.invalidTitle', '入力エラー', 'ja'),
                                                              ('alert.invalidNonNegative', '価格と数量は0以上でなければなりません。', 'ja'),
                                                              ('alert.invalidNumber', '有効な価格と数量を入力してください。', 'ja'),
                                                              ('alert.successTitle', '成功', 'ja'),
                                                              ('alert.errorTitle', 'エラー', 'ja'),
                                                              ('message.saved', 'カートが正常に保存されました。', 'ja'),
                                                              ('message.error', '問題が発生しました。', 'ja');


INSERT INTO localization_strings (`key`, value, language) VALUES
                                                              ('app.title', 'تطبيق سلة التسوق', 'ar'),
                                                              ('label.language', 'اختر اللغة', 'ar'),
                                                              ('label.itemName', 'اسم المنتج', 'ar'),
                                                              ('label.price', 'السعر', 'ar'),
                                                              ('label.quantity', 'الكمية', 'ar'),
                                                              ('label.overallTotal', 'السعر الإجمالي', 'ar'),
                                                              ('prompt.itemName', 'أدخل اسم المنتج', 'ar'),
                                                              ('prompt.price', 'أدخل السعر', 'ar'),
                                                              ('prompt.quantity', 'أدخل الكمية', 'ar'),
                                                              ('button.addItem', 'إضافة منتج', 'ar'),
                                                              ('button.calculate', 'احسب', 'ar'),
                                                              ('button.clear', 'مسح', 'ar'),
                                                              ('button.save', 'حفظ السلة', 'ar'),
                                                              ('table.name', 'الاسم', 'ar'),
                                                              ('table.price', 'السعر', 'ar'),
                                                              ('table.quantity', 'الكمية', 'ar'),
                                                              ('table.total', 'الإجمالي', 'ar'),
                                                              ('default.itemName', 'منتج', 'ar'),
                                                              ('alert.invalidTitle', 'إدخال غير صالح', 'ar'),
                                                              ('alert.invalidNonNegative', 'يجب أن يكون السعر والكمية صفراً أو أكثر.', 'ar'),
                                                              ('alert.invalidNumber', 'يرجى إدخال سعر وكمية صالحين.', 'ar'),
                                                              ('alert.successTitle', 'نجاح', 'ar'),
                                                              ('alert.errorTitle', 'خطأ', 'ar'),
                                                              ('message.saved', 'تم حفظ سلة التسوق بنجاح!', 'ar'),
                                                              ('message.error', 'حدث خطأ ما.', 'ar');